# Generated by Django 4.2.6 on 2023-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(default='mdefaulycode', max_length=20),
            preserve_default=False,
        ),
    ]
