# Generated by Django 4.2.6 on 2023-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_url_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='empty_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='timestap',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
