# Generated by Django 4.2.6 on 2023-10-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_url_active_alter_url_shortcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
