# Generated by Django 4.2.6 on 2023-10-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_url_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='empty_datetime',
        ),
    ]
